name: Build and push Docker images
on:
  push:
    branches: [ master ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: test_github_actions
          registry: 763060245531.dkr.ecr.us-east-1.amazonaws.com
          dockerfile: ./Dockerfile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_VOXY_ECR_USER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_VOXY_ECR_USER_SECRET_ACCESS_KEY }}
#      - name: Push to ECR
#        id: ecr
#        uses: jwalton/gh-ecr-push@v1
#        with:
#          access-key-id: ${{ secrets.AWS_VOXY_ECR_USER_ACCESS_KEY_ID }}
#          secret-access-key: ${{ secrets.AWS_VOXY_ECR_USER_SECRET_ACCESS_KEY }}
#          region: us-east-1
#          image: my-image:v1
